version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: hp_nginx
    depends_on:
      - php
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
  php:
    build: .
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
    container_name: hp_app
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: hp_mysql
    tty: true
    ports:
      - "3939:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - app-network
  # postgres:
  #   image: postgres:16.3
  #   restart: unless-stopped
  #   container_name: hp_postgres
  #   tty: true
  #   ports:
  #     - "4949:5432"
  #   volumes:
  #     - ./.deployment/postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: xI2GVJn6qfzeNMm
  #   networks:
  #     - hapo-network

volumes:
  vendor:
  storage:
  mysql-data:

networks:
  app-network:
    driver: bridge