version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: hp_nginx
    depends_on:
      - php
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./.deployment/nginx/:/etc/nginx/conf.d/
    networks:
      - hapo-network
  php:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: hp_app
    networks:
      - hapo-network
  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    container_name: hp_mysql
    tty: true
    ports:
      - "3939:3306"
    volumes:
      - ./.deployment/mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: xI2GVJn6qfzeNMm
    networks:
      - hapo-network
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    container_name: hp_postgres
    tty: true
    ports:
      - "4949:5432"
    volumes:
      - ./.deployment/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xI2GVJn6qfzeNMm
    networks:
      - hapo-network

networks:
  hapo-network:
    driver: bridge